# Generated by Django 6.0.3 on 2026-06-21 21:07

from django.db import migrations


def set_existing_teachers_verified(apps, schema_editor):
    UserProfile = apps.get_model('authentication', 'UserProfile')
    UserProfile.objects.filter(role='teacher').update(email_verified=True)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_teachers_verified, migrations.RunPython.noop),
    ]
