# Generated by Django 6.0.2 on 2026-05-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_exam_attempts'),
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('per_question', 'Per question'), ('total', 'Total')], max_length=20)),
                ('per_question_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timing', to='classroom.classroom')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timing_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
